// Re-export types that will be available after generation
// These are placeholder types - the actual types will be generated by the CLI

export interface TranslationOptions {
  defaultValue?: string;
  count?: number;
  context?: string;
  replace?: Record<string, unknown>;
  [key: string]: any;
}

// This will be replaced by generated types
export type TranslationKey = string;

export interface TypedTFunction {
  (key: TranslationKey, options?: TranslationOptions): string;
}

// Namespace type - will be replaced by generated types
export type TranslationNamespace = string;
