// Re-export types that will be available after generation
// These are placeholder types - the actual types will be generated by the CLI

export interface TranslationOptions {
  defaultValue?: string;
  count?: number;
  context?: string;
  replace?: Record<string, unknown>;
  [key: string]: any;
}

// Generic function type that works with any string type
export interface TypedTFunction<T extends string = string> {
  (key: T, options?: TranslationOptions): string;
}

// Note: TranslationKey and TranslationNamespace are generated by the CLI
// and should be imported from the generated files, not from this package
